// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> en = {
  "login": "Login",
  "welcome": "Welcome!",
  "enter_phone": "Enter your phone number to continue",
  "create_new_account": "Create a new account",
  "surname": "Surname",
  "name": "Name",
  "patronymic": "Patronymic",
  "terms_of_use": " terms of use",
  "i_accept": "I accept the",
  "i_have_account": "I have an account.",
  "create_account": "Create account",
  "verification_code": "Verification code",
  "enter_otp_code": "Enter the verification code sent to your phone number",
  "resend": "Resend",
  "phone_number": "Phone number",
  "full_name": "Full name",
  "card_number": "Card number",
  "card_expiration_date": "Card expiration date",
  "passport_serie": "Passport series",
  "passport_number": "Passport number",
  "settings": "Settings",
  "my_profile": "My profile",
  "dark_mode": "Dark mode",
  "system_theme": "System theme",
  "privacy": "Privacy",
  "about_us": "About us",
  "support": "Support",
  "language": "Language",
  "logout": "Logout",
  "borrows": "Borrows",
  "borrow_types": "Borrow types",
  "get_loan": "Get loan",
  "my_borrowings": "My borrowings",
  "consumer_credit": "Consumer credit",
  "no_history": "No history",
  "percent": "Interest rate:",
  "duration": "Duration:",
  "value": "Value:",
  "average_cost": "Average monthly cost:",
  "bank_answer": "Bank answer",
  "choose_guarantor": "Choose guarantor",
  "personal_guarantor": "Personal guarantor",
  "government_guarantor": "State Insurance Organization of Turkmenistan",
  "apply_for_loan": "Apply for a loan",
  "loan_value": "Loan value",
  "loan_duration": "Loan duration",
  "year": "year",
  "one_year": "1 year",
  "two_year": "2 years",
  "three_year": "3 years",
  "upto_x_manat": "Up to {limit} manat",
  "has_credit_card_before": "Do you have a credit card?",
  "yes_i_have": "Yes",
  "no": "No",
  "yes": "Yes",
  "account_id": "Account ID",
  "passport_issuer": "Passport issuer",
  "passport_issue_date": "Passport issue date",
  "passport_address": "Residential address (as shown in the passport)",
  "approve": "Approve",
  "credit_type": "Credit type",
  "credit_info_how_determined_monthly_payment": "The amount of the monthly payment is determined according to the term of the loan.",
  "dialog_title_credit_successfullt_sent": "Your request has been submitted successfully",
  "dialog_subtitle_credit_successfullt_sent": "You can view the result of your request on the main page of the app shortly",
  "checking": "Checking",
  "accepted": "Accepted",
  "declined": "Declined",
  "sent": "Sent",
  "continue_": "Continue",
  "choose_lang": "Choose language",
  "letter": "Your message",
  "for_calling_support": "For contacting support:",
  "send": "Send",
  "new": "New",
  "error_occured": "Something went wrong!",
  "otp_wrong": "Incorrect verification code!",
  "user_exist_error": "This user account already exists. Please log in!",
  "status_checking_desc": "Your request is under review",
  "status_accepted_desc": "Your request has been successfully approved\nTo receive the loan, please come to the “Halk Bank” branch with all necessary documents\nYou can find the necessary documents in the Loan section of the program\nFor more information, you can contact the following numbers (09:00 - 18:00)\n(99312) 44-48-37\n(99312) 22-73-23",
  "status_declined_desc": "Sorry, we couldn't approve your request at the moment\nFor more information, you can contact the following numbers (09:00 - 18:00)\n(99312) 44-48-37\n(99312) 22-73-23\nOr come to the “Halk Bank” branch nearest you",
  "status_new_desc": "Your request has been received, please wait for a while.",
  "status_sent_desc": "Your request has been sent",
  "fill_data_error": "Please fill in the data!",
  "user_not_found": "User not found, please create account first",
  "my_infos": "My Information",
  "guarantor_infos": "Guarantor Information",
  "guarantor": "Guarantor:",
  "logout_desc": "Do you really want to log out?",
  "bank_address": "744013, Turkmenistan, Ashgabat, st. Hero of Turkmenistan Atamyrat Niyazov, 154\n",
  "info_1": "1 guarantor",
  "info_2": "50% from salary of borrower and guarantor to repay the loan and interest on it (or 50% from total family income)",
  "info_3": "Cash or non-cash method",
  "info1_key": "Ensuring loan repayment",
  "info2_key": "Loan repayment source",
  "info3_key": "Repayment methods",
  "about_us_desc": "In order to meet the needs of our clients in banking services, that is the main and most important goal of our activities, the bank performs the following complex tasks:\nEffective implementation of investment and monetary policy, support and development of small and medium sized entrepreneurship;\nImplementation of state policy in the field of savings business;\nProtection of the interests of depositors and clients of the bank; ensuring the complete safety of funds and other valuables of the population entrusted to the bank, and issuing them at the first request of depositors;\nProviding bank services for citizens of Turkmenistan and foreign citizens on convenient terms and conditions;\nPromotion of economic and social development of Turkmenistan as well as successful introduction in international bank system.\n\nGoals of the bank\nIncreasing the number of private and corporate clients;\nOffering complex bank products and services to private and corporate clients;\nOffering financial services that meet high standards of the modern financial market;\nQualified performance of offered services in a short time;\n\nDevelopment and improvement of bank operations technologies and services.\nValues of the banks\nThe trust of clients We are working for maintain our greatest value – the trust of clients.\nReliability We are combining strong positions in the financial market and historical experience. This is a guarantee of our reliability and stability.\nOpenness and benevolence We are striving to open and trusting partnership with our clients, we are accessible and understandable.\nUniversality We are offering comprehensive solutions of any level complexity due to our experience and strong positions in various segments of financial market.\nProfessionalism We are strong by unity of our staff – knowledge, energy, potential and creativity of everyone makes our team strong and unique"
};
static const Map<String,dynamic> ru = {
  "login": "Вход",
  "welcome": "Добро пожаловать!",
  "enter_phone": "Введите ваш номер телефона, чтобы продолжить",
  "create_new_account": "Создать новый аккаунт",
  "surname": "Фамилия",
  "name": "Имя",
  "patronymic": "Отчество",
  "terms_of_use": " условия использования",
  "i_accept": "Я принимаю ",
  "i_have_account": "У меня уже есть аккаунт.",
  "create_account": "Создать аккаунт",
  "verification_code": "Код подтверждения",
  "enter_otp_code": "Введите код подтверждения, отправленный на ваш номер телефона",
  "resend": "Отправить еще раз",
  "phone_number": "Номер телефона",
  "full_name": "Полное имя",
  "card_number": "Номер карты",
  "card_expiration_date": "Срок действия карты",
  "passport_serie": "Серия паспорта",
  "passport_number": "Номер паспорта",
  "settings": "Настройки",
  "my_profile": "Мой профиль",
  "dark_mode": "Темный режим",
  "system_theme": "Тема системы",
  "privacy": "Конфиденциальность",
  "about_us": "О нас",
  "support": "Поддержка",
  "language": "Язык",
  "logout": "Выйти",
  "borrows": "Займы",
  "borrow_types": "Типы займов",
  "get_loan": "Получить займ",
  "my_borrowings": "Мои займы",
  "consumer_credit": "Потребительский кредит",
  "no_history": "Нет истории",
  "percent": "Процентная ставка:",
  "duration": "Срок:",
  "value": "Сумма:",
  "average_cost": "Средний месячный платеж:",
  "bank_answer": "Ответ банка",
  "choose_guarantor": "Выберите поручителя",
  "personal_guarantor": "Личный поручитель",
  "government_guarantor": "Государственная страховая организация Туркменистана",
  "apply_for_loan": "Подать заявку на кредит",
  "loan_value": "Сумма кредита",
  "loan_duration": "Срок кредита",
  "year": "год",
  "one_year": "1 год",
  "two_year": "2 года",
  "three_year": "3 года",
  "upto_x_manat": "До {limit} манат",
  "has_credit_card_before": "У вас есть кредитная карта?",
  "yes_i_have": "Да",
  "no": "Нет",
  "yes": "Да",
  "account_id": "Идентификатор аккаунта",
  "passport_issuer": "Кем выдан паспорт",
  "passport_issue_date": "Дата выдачи паспорта",
  "passport_address": "Адрес проживания (как указано в паспорте)",
  "approve": "Подтвердить",
  "credit_type": "Тип кредита",
  "credit_info_how_determined_monthly_payment": "Размер ежемесячного платежа определяется в соответствии с условиями кредита.",
  "dialog_title_credit_successfullt_sent": "Ваш запрос успешно отправлен",
  "dialog_subtitle_credit_successfullt_sent": "Вы сможете увидеть результат вашего запроса на главной странице приложения в ближайшее время",
  "checking": "Проверка",
  "accepted": "Принято",
  "declined": "Отклонено",
  "sent": "Отправлено",
  "continue_": "Продолжить",
  "choose_lang": "Выберите язык",
  "letter": "Ваше сообщение",
  "for_calling_support": "Для связи с поддержкой:",
  "send": "Отправить",
  "new": "Новый",
  "error_occured": "Что-то пошло не так!",
  "otp_wrong": "Неверный код подтверждения!",
  "user_exist_error": "Этот аккаунт пользователя уже существует. Пожалуйста, войдите!",
  "status_checking_desc": "Ваш запрос на рассмотрении",
  "status_accepted_desc": "Ваш запрос успешно одобрен\nДля получения кредита, пожалуйста, приходите в отделение «Halk Bank» с необходимыми документами\nВы можете найти необходимые документы в разделе Кредит программы\nДля получения дополнительной информации, пожалуйста, свяжитесь по следующим номерам телефонов (09:00 - 18:00)\n(99312) 44-48-37\n(99312) 22-73-23",
  "status_declined_desc": "Извините, мы временно не можем одобрить ваш запрос\nДля получения дополнительной информации, пожалуйста, свяжитесь по следующим номерам телефонов (09:00 - 18:00)\n(99312) 44-48-37\n(99312) 22-73-23\nИли приходите в ближайшее к вам отделение «Halk Bank»",
  "status_new_desc": "Ваш запрос получен, пожалуйста, подождите некоторое время.",
  "status_sent_desc": "Ваш запрос отправлен",
  "fill_data_error": "Пожалуйста, заполните данные!",
  "user_not_found": "Пользователь не найден, пожалуйста, сначала создайте аккаунт",
  "my_infos": "Мои данные",
  "guarantor_infos": "Информация о поручителе",
  "guarantor": "Поручитель:",
  "logout_desc": "Вы действительно хотите выйти?",
  "bank_address": "744013, Туркменистан, г.Ашхабад, ул. Героя Туркменистана Атамурата Ниязова, 154\n",
  "info_1": "1 поручитель",
  "info_2": "50% от зарплаты заемщика и поручителя для погашения кредита и процентов по нему (или 50% от общего семейного дохода)",
  "info_3": "Наличным или безналичным способом",
  "info1_key": "Обеспечение возврата кредита",
  "info2_key": "Источник погашения кредита",
  "info3_key": "Способ погашения",
  "about_us_desc": "Для удовлетворения потребностей наших клиентов в банковских услугах - это основная и самая важная цель нашей деятельности. Банк выполняет следующие комплексные задачи:\n\nЭффективное осуществление инвестиционной и денежной политики, поддержка и развитие малого и среднего предпринимательства;\nРеализация государственной политики в сфере сберегательного бизнеса;\nЗащита интересов вкладчиков и клиентов банка; обеспечение полной безопасности средств и других ценностей населения, доверенных банку, и их выдача по первому требованию вкладчиков;\nПредоставление банковских услуг гражданам Туркменистана и иностранным гражданам на удобных условиях;\nСодействие экономическому и социальному развитию Туркменистана, а также успешное внедрение в международную банковскую систему.\n\nЦели банка\nУвеличение числа частных и корпоративных клиентов;\nПредложение комплексных банковских продуктов и услуг частным и корпоративным клиентам;\nПредложение финансовых услуг, отвечающих высоким стандартам современного финансового рынка;\nКвалифицированное выполнение предлагаемых услуг в короткие сроки;\n\nРазвитие и совершенствование технологий и услуг банковской деятельности.\n\nЦенности банка\nДоверие клиентов. Мы работаем, чтобы сохранить наш самый великий ценности - доверие клиентов.\n\nНадежность. Мы объединяем сильные позиции на финансовом рынке и исторический опыт. Это гарантия нашей надежности и стабильности.\n\nОткрытость и доброжелательность. Мы стремимся к открытому и доверительному партнерству с нашими клиентами, мы доступны и понятны.\n\nУниверсальность. Мы предлагаем комплексные решения любой сложности благодаря нашему опыту и сильным позициям в различных сегментах финансового рынка.\n\nПрофессионализм. Мы сильны благодаря единству нашего персонала - знания, энергия, потенциал и творчество каждого делают нашу команду сильной и уникальной."
};
static const Map<String,dynamic> tk = {
  "login": "Ulgama girmek",
  "welcome": "Hoş geldiňiz!",
  "enter_phone": "Dowam etmek üçin telefon belgiňizi giriziň",
  "create_new_account": "Täze hasap döretmek",
  "surname": "Familiýasy",
  "name": "Ady",
  "patronymic": "Atasynyň ady",
  "terms_of_use": " kabul edýärin",
  "i_accept": "Ulanyş düzgünlerini",
  "i_have_account": "Hasabym bar.",
  "create_account": "Hasap döretmek",
  "verification_code": "Tassyklaýjy kody",
  "enter_otp_code": "Telefon belgiňize baran tassyklaýjy kody giriziň",
  "resend": "Täze kod ibermek",
  "phone_number": "Telefon belgisi",
  "full_name": "FAA",
  "card_number": "Kart belgisi",
  "card_expiration_date": "Kartyň möhleti",
  "passport_serie": "Pasport seriýasy",
  "passport_number": "Pasport belgisi",
  "settings": "Sazlamalar",
  "my_profile": "Meniň profilim",
  "dark_mode": "Garaňky tema",
  "system_theme": "Sistema temasy",
  "privacy": "Ulanyş kadalary",
  "about_us": "Biz barada",
  "support": "Habarlaşmak",
  "language": "Dil",
  "logout": "Ulgamdan çykmak",
  "borrows": "Karzlar",
  "borrow_types": "Karzlaryň görnüşleri",
  "get_loan": "Karz almak",
  "my_borrowings": "Meniň karzlarym",
  "consumer_credit": "Sarp ediş karzy",
  "no_history": "Sizde entek karz ýok",
  "percent": "Göterimi:",
  "duration": "Möhleti:",
  "value": "Möçberi:",
  "average_cost": "Ortaça aýlyk tölegiňiz:",
  "bank_answer": "Bankyň jogaby",
  "choose_guarantor": "Zamunçy saýlamak",
  "personal_guarantor": "Şahsy zamunçy",
  "government_guarantor": "Türkmenistanyň döwlet ätiýaçlandyryş guramasy",
  "apply_for_loan": "Karz almak üçin ýüzlenme",
  "loan_value": "Karzyň möçberi",
  "loan_duration": "Karzyň möhleti",
  "year": "ýyl",
  "one_year": "1 ýyl",
  "two_year": "2 ýyl",
  "three_year": "3 ýyl",
  "upto_x_manat": "{limit} manada çenli",
  "has_credit_card_before": "Siziň kredit kartyňyz barmy?",
  "yes_i_have": "Bar",
  "yes": "Hawa",
  "no": "Ýok",
  "account_id": "Hasap belgiňiz",
  "passport_issuer": "Pasport berilen ýeri",
  "passport_issue_date": "Pasport berilen senesi",
  "passport_address": "Ýaşaýan salgysy (Pasportda görkezilen)",
  "approve": "Tassyklamak",
  "credit_type": "Karzyň görnüşi",
  "credit_info_how_determined_monthly_payment": "Karzyň möhletine görä her aýdaky tölegiň möçberi kesgitlenýär.",
  "dialog_title_credit_successfullt_sent": "Siziň amalyňyz kabul edildi",
  "dialog_subtitle_credit_successfullt_sent": "Amalyňyzyň netijesini gysga wagtyň içinde programmanyň baş sahypasynda görüp bilersiňiz",
  "checking": "Barlanylýar",
  "accepted": "Tassyklandy",
  "declined": "Ret edildi",
  "sent": "Iberildi",
  "continue_": "Dowam et",
  "choose_lang": "Dili saýlaň",
  "letter": "Hatyňyz",
  "for_calling_support": "Jaň arkaly habarlaşmak üçin:",
  "send": "Iber",
  "new": "Täze",
  "error_occured": "Näsazlyk ýüze çykdy!",
  "otp_wrong": "Tassyklaýyş kody nädogry!",
  "user_exist_error": "Bu ullanyjyň hasaby eýýäm bar. Ulgama girmegiňizi haýyş edýäris!",
  "status_checking_desc": "Siziň arzaňyz barlanylýar",
  "status_accepted_desc": "Siziň arzaňyz üstünlikli tassyklanyldy\nKarz almak üçin ähli zerur resminamalary ýygnap size iň amatly bolan “Halk Bank” şahamçasyna geliň\nGerekli resminamalary programmanyň Karzyň görnüşleri bölüminde tapyp bilersiňiz\nSebäbini bilmek üçin aşakdaky belgilere (09:00 - 18:00) jaň edip bilersiňiz\n(99312) 44-48-37\n(99312) 22-73-23 ",
  "status_declined_desc": "Bagyşlaň, häzirki wagtda arzaňyzy tassyklap bilmedik\nSebäbini bilmek üçin aşakdaky belgilere (09:00 - 18:00) jaň edip bilersiňiz\n(99312) 44-48-37\n(99312) 22-73-23\nÝa-da Size iň amatly bolan “Halk Bank” şahamçasyna geliň",
  "status_new_desc": "Siziň arzaňyz bize gowuşdy biraz garaşmagyňyzy haýyş edýäris.",
  "status_sent_desc": "Siziň arzaňyz iberildi",
  "fill_data_error": "Maglumatlary dolduryň!",
  "user_not_found": "Telefon belgiňiz hasaba alynmadyk.",
  "my_infos": "Maglumatlarym",
  "guarantor_infos": "Zamunçy maglumatlary",
  "guarantor": "Zamunçy:",
  "logout_desc": "Siz hakykatdan hem hasabyňyzdan çykmak isleýärsiňizmi?",
  "bank_address": "744013, Türkmenistan, ş.Aşgabat, Türkmenistanyň Gahrymany Atamyrat Nyýazow şaýoly, 154\n",
  "info_1": "1 raýatyň zamun durmagy",
  "info_2": "Karzy we göterimleri üzmek üçin karzdaryň zähmet hakyndan 50% göterime çenli alynýar ( ýa-da maşgalanyň umumy girdejisiniň 50%)",
  "info_3": "Nagt we nagt däl pul serişdeleri",
  "info1_key": "Karzy gaýtarmagyň üpjünçiligi",
  "info2_key": "Karzy üzmegiň çeşmeleri",
  "info3_key": "Karzy üzmegiň usuly",
  "about_us_desc": "Müşderilerimiziň isleglerini kanagatlandyrmak - bu biziň çekýän zähmetimiziň baş we wajyp wezipesi bolmak bilen, onuň çäklerinde bank aşakdaky toplumlaýyn işleri ýerine ýetirýär:\nMaýa goýum we karz-pul syýasatyny netijeli durmuşa ornaşdyrmak, kiçi we orta telekeçiligi goldamak we ösdürmek;\nDöwletiň süýşürintgiler syýasatyny durmuşa geçirmek;\nGoýumçylaryň we müşderileriň bähbitlerini goramak; ilatyň banka ynanylan pul serişdeleriniň we beýleki gymmatlyklarynyň doly abat saklanylmagyny hem-de olaryň goýumçylaryň ilkinji talaby boýunça berilmegini üpjün etmek;\nTürkmenistanyň we daşary ýurtlaryň raýatlaryna amatly şertli hyzmatlary hödürlemek;\nTürkmenistanyň durmuş – ykdysady ösüşine we halkara bank düzümine oňaýly goşulyşmagyna ýardam bermek.\n\nBankyň maksady\nŞahsy we korporatiw müşderileri artdyrmak;\nŞahsy we korporatiw müşderilere toplumlaýyn bank önümlerini we hyzmatlaryny hödürlemek;\nDöwrebap maliýe bazarynyň ýokary derejeli standartlaryna laýyk gelýän maliýe hyzmatlaryny hödürlemek;\nHödür edilýän hyzmatlary tiz we ýokary hilli amala aşyrmak;\nBank amallarynyň we hyzmatlarynyň tilsimatlaryny ösdürmek we kämilleşdirmek.\n\nBankyň gymmatlyklary\nMüşderileriň ynamy Biz esasy gymmatlygymyz bolan müşderilerimiziň ynamany ödemek üçin işleýäris.\nYgtybarlylyk Biz maliýe bazaryndaky berk ornumyzy taryhy tejribe bilen utgaşdyrýarys. Bu biziň ygtybarlylygymyzyň we durnuklylygymyzyň ke.\nAçykgöwünlilik we hoşniýetlilik Biz müşderilerimiz bilen açyk we ynamdar hyzmatdaşlyga ymtylýarys, müşderiler üçin biz elýeterli we amatly.\nKöptaraplylyk Biz maliýe bazarynyň dürli pudaklarynda berk ornumyza we tejribämize daýanyp dürli derejeli toplumlaýyn çözgütleri hödürlerýäris.\nUssatlyk Biziň güýjümiz işgärlerimiziň agzybirliginde — her bir işgäriň bilimi, işjeňligi, mümkinçiligi we döredijiligi biziň kollektiwimizi güýçli edýär we oňa özboluşlyk berýär."
};
static const Map<String, Map<String,dynamic>> mapLocales = {"en": en, "ru": ru, "tk": tk};
}
